clang-tidy-cache
Hello, thank you for the tool!
I'm trying adopting it in https://github.com/ClickHouse/ClickHouse/pull/42913, but we don't have a user in docker images, and the `CTCACHE_DIR` environment variable doesn't work
```
(Pdb) is_cached(opts, digest)
*** KeyError: 'getpwuid(): uid not found: 1000'
```
Here I try fixing it. As well as reduce the load in `cache_dir` by making it a property
=> Make cache_dir a property, fix `KeyError: "getpwuid(): uid not found:"`

clang-tidy-cache
Since `boto3` is a quite heavy module with many dependencies, it makes sense to make it optional.
It fixes #6
=> Make `import boto3` an optional only when bucket is defined

clang-tidy-cache
ctcache works great for the case where compiler arguments are passed on the clang-tidy command line in the form `clang-tidy file.cpp -- gcc -DBLAH=1 file.cpp`, however it does not deal with the (relatively common, I expect) case where the `-p` argument is used, whereby clang-tidy sources the compiler arguments from a `compile_commands.json` file that was generated during compilation. This PR adds the functionality to detect when `-p` is used, and loads and reads from the compile commands DB as necessary.
=> Add support for loading compiler args when clang-tidy is invoked with -p

clang-tidy-cache-server, requirements.txt
Parameters for send_from_director that were depreated in Flask 2.0.0 were completely dropped in 2.2.0: https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-2-0
So 'filename' is not a legit name anymore.
I guess it was left in https://github.com/matus-chochlik/ctcache/commit/3ff698f7f87055042cace71321ffc3042337bae3 to be compatible with both modern and old flask. Looks like this is not that easy these days, but maybe now it is ok to require flask >= 2.0.0 and drop legacy parameter name.
And in addition, we can specify `download_name`
=> Adjust clang-tidy-cache-server for modern flask

README.md, clang-tidy-cache
In our infrastructure, we can't use direct http connections even between internal services on different machines. In case of ctcache, all connections go via nginx https proxy which is configured in a way that doesn't accept pure http (`400 Bad Request "the plain http request was sent to https port"`). The easiest way for us to solve this issue is to use 'https' in ctcache when connecting to the server.
=> Add possibility to specify https instead of http via CTCACHE_PROTO

clang-tidy-cache
+ Do not print error message if server returned 'false' string
There was a mistake in my previous PR, CTCACHE_PROTO should not be cast to int.
In addition, the server returns 'false' string if cache not found. When we launch `json()` for such response, we get `False` value. The current code treats this as a server connection error, but this is not correct and looks confusing.
=> Do not treat CTCACHE_PROTO as int

clang-tidy-cache
I just lacked these features to start using this script.
Сcache can use redis out of the box. And usually when people start looking for something for clang-tidy they already have redis setted up for ccache.
I also need the saved error output.
=> Add redis and ability to save stdout

clang-tidy-cache, example/CMakeLists.txt
I changed the way the hash is created in `hash_inputs()` because building a project with VSCode and Ninja outputs many thousands of lines of code when running this part of the original code:
```python
proc = subprocess.Popen(
co_args,
stdout=subprocess.PIPE,
stderr=subprocess.PIPE
)
stdout, stderr = proc.communicate()
if stderr:
return None
```
which causes the project to hang indefinately.
I also noticed that `stdout` and `stderr` get switched around when compiling with cl.exe vs clang.exe although I can no longer be sure that was the case.
The method now calculates the hash with the time the source file was last modified, the lines within any .clang-tidy config files, and then the args. The last two are more or less the same as the original code although the method I use to find the …
=> Changed the way the hash is created in `hash_inputs()`

clang-tidy-cache
Currently `samefile` is used to check if a file present in the `compile_commands.json` database matches one of the files passed on the command line to `clang-tidy-cache`. However, this causes some issues in the case of generated files, as [samefile](https://docs.python.org/3/library/os.path.html#os.path.samefile) can raise exceptions if one file does not exist. Since our setup is to generate the compile commands database without compiling anything, that database contains references to files that do not exist yet. These files crash clang-tidy-cache.
The fix I'm proposing is simple: if `samefile` throws a `FileNotFoundError`, just consider that the files don't match and continue.
=> Ignore errors in samefile

clang-tidy-cache
This PR adjusts the hash computation such that it include the output of the Clang preprocessor instead of the source file modification file (the latter not being sensitive to changes in included headers).
=> Add preprocessor output to hash computation

clang-tidy-cache
* Support --show-stats without server
* Add configurable dump dir
* Allow excluding args using regex (In my case I didn't want a different build number define to cause a cache miss)
Fixes #3
=> Local stats

clang-tidy-cache
In a recent PR #33 , support for local stats was added. However, those stats are not updated when `CTCACHE_SAVE_OUTPUT` is set, as we don't call `is_cached` but `get_cache_data`. Thus, I added the necessary calls to `update_stats` to update the stats even when used with the data.
=> Update stats when used with data

clang-tidy-cache
This add `.cc` as a valid CPP file extension.
Looking at https://gcc.gnu.org/onlinedocs/gcc/Overall-Options.html there is some additional extansion that could be added but this fixes this for us and others using Google Code Style guidelines.
=> Add .cc as valid CPP file extension

clang-tidy-cache
Currently, an empty string/entry is ignored by `ClangTidyCache.get_cache_data`, resulting in `None` being returned.
Thus, a cache hit will be ignored and clang-tidy still run if the entry is empty and `save_output` is enabled.
This also contrasts [`run_clang_tidy_cached`](https://github.com/N-Coder/ctcache/blob/a8dbb5c70d15eb513e55ff28c0ac46b13b7a5e9d/clang-tidy-cache#L1092) that correctly checks `if data is not None` instead of only `if data`.
=> do not ignore cache data if it is empty

clang-tidy-cache
The file lock was acquired and release twice, once to read the stats file, and once to write the stats file. As such, writes can get lost.
I was looking at https://github.com/matus-chochlik/ctcache/issues/36 which we hit in our system, so I extracted the locking code into a separate file, launched a 100 parallel copies of the test, and observed that stats file having `74`, `58` etc. as opposed to a guaranteed `100`.
This fix only acquires the file lock once, which could reduce the lock contention that has been observed, and reads, updates, and writes the stats under the lock. This fixes the atomicity of the stats updates as well.
=> Make local stats update atomic.

clang-tidy-cache
This error not being logged or raised made finding the reason why ctcache wasn't working a bit painful.
I thought about raising an exception here but didn't want to break existing behaviour. If you prefer an exception i'll change it.
=> Logging compile commands error

clang-tidy-cache
I ran into an issue when using ccache.
My compile_commands.json looks like this
"command": "/usr/bin/ccache  clang++ -DBOOST_PROPERTY_TREE_RAPIDXML_STATIC_POOL_SIZE=1024  -D ......"
clang-tidy-cache tries to put -D__clang_analyzer option in position 1 which is before 'clang++' which causes an error, and doesn't carry on with the hash.
It now puts the -D option before the first -D option, or the existing position 1 as the default.
This error was also hidden as stderr isn't logged. The hash function just returns None.  I was going to create a separate PR for that, but could put it in this one if needed.
=> Insert the clang_analyzer option before the first -D command line option

clang-tidy-cache
Avoid duplicate file open/close activity in the common case of updating the stats file under the lock. Instead, check if the file exists and open it with `r+` mode to make in-place edits. Otherwise, if the file does not exist, open it with `w` mode to write the initial stats.
=> Further reduce stats lock contention

clang-tidy-cache-server, static/ctcache.css, static/index.html
A couple of issues for the ctcache web ui (found and fixes tested on chrome, firefox on mac)
1. The images were created with a dark theme so the labels/axis have a white font. No background colour was set so the background would default to white, and hide the axis etc.  The fix sets the background colour to the same colour as on the example image on github.
2. Some webpage aspect ratios would hide the y axis labels of the grids. Resizing the webpage smaller and with more width than height would resize the images in a way that the y axis labels would be shown again. This changes how the images are saved and the images now show the y label for all webpage height/widths.
=> Fixing web background and image clipping issues

clang-tidy-cache
I was looking into https://github.com/matus-chochlik/ctcache/issues/36 again as it showed up in our CI build system recently. This PR has a minor tweak.
The better approach would likely be to move away from the single lock and maybe use the `digest[:2]`-based paths to keep hit/miss stats for each of the 256 buckets. This reduces the contention in the (frequent) update path, at the expense of the (infrequent) `read` and `clear` paths having to enumerate the folders.
=> Avoid repeated recalculation of stats file name

README.md, clang-tidy-cache
Supersedes https://github.com/matus-chochlik/ctcache/pull/54 and implements https://github.com/matus-chochlik/ctcache/issues/53 in a better way.
~~This PR is still in draft because I'm planning to do more extensive testing over here, but it shows the proposed approach as outlined in the linked issue.~~ I've tested the behavior in our CI system and on local developer machines, and it works as advertised in the linked issue.
Some refactorings are done to make the caches a bit more compositional:
* `ClangTidyMultiCache` implements the cache interface over an array of caches.
* `ClangTidyCacheWithStats` is a decorator around a cache that adds hit/miss counters.
* `ClangTidyCacheStats` is the generalization of the original "local stats".
* `ClangTidyLocalCache` has its statistics logic …
=> Restructure local/remote cache and support write-back to local cache upon remote cache hit

README.md, clang-tidy-cache
Add option `CTCACHE_STRIP_SRC` to also strip paths defined in `CTCACHE_STRIP` from source files.
Converts standard string replace to regex substitution as it is factors faster, especially on the large source inputs
=> feat: Add option to also strip paths from source files

clang-tidy-cache, clang-tidy-cache-server
The output of clang tidy is saved on the server in files that have the name of the calculated hash. For data that was not saved before the reboot, a separate cleaning function was made - "_do_cleanup_invalid". To control memory on the server, the "--max-cache-size" or "-M" flag was added. Using this flag, you can configure the approximate size of disk space allowed for use. Also added is the removal of files that have not been used for the longest time, which is reflected in the "_do_cleanup_least_recently_used" function.
The response for the client is either a 200 response; if the response has a different status, then there is no data or the request is not valid.
It might be better not to use a custom python server, but to use high-performance nginx, as is done, for example, in ccache > …
=> Add save output for server cache storage

README.md, src/ctcache/clang_tidy_cache.py
In our code base we have a list of generated code files and third party libraries. We don't have control over them meaning that some of them contain warnings. However, we do filter them out using run-clang-tidy.py. This means that clang-tidy itself sometimes runs with exit code != 0 but that's OK. So I would like the ctcache to cope with such situations. 
The approach taken here is to extend the `CTCACHE_SAVE_OUTPUT` option. In the cached output always reserve the first byte for clang-tidy's exit code. The following bytes remain the same. This change by itself doesn't help a lot since the output is anyway just stored if the exit code is ==0. So, the new behavior is introduced by enabling the new `CTCACHE_SAVE_ALL` (or however you might want to call this option) which caches the output …
=> Introduce option CTCACHE_SAVE_ALL to save clang-tidy's output even in case of errors

src/ctcache/clang_tidy_cache.py
In the server configuration we use, the Redis user used to read and write the ctcache stuff has only minimal permissions. By default redis-py always sends some `CLIENT SETINFO ...` commands to the server. In our case this results in errors. I think these commands can be avoid in case of ctcache. 
Of course, this could be made configurable, but I guess it's favorable to not overwhelm the user by configuration options. Therefore, I think this would make a good default.
=> Constrain commands to the Redis server to the bare minimum: AUTH, GET, SET

clang-tidy
In 05f3db7c716eba8cbbdbba880fc1aedb84a67654 (move to src-layout), the file permission of `clang-tidy-cache.py` is 644; before that the `clang-tidy-cache` script had 755. This caused the `clang-tidy` script to fail when invoking `clang-tidy-cache.py`.
Run the script via `/usr/bin/env python3` (equivalent to the shbang in `clang-tidy-cache.py`) to fix this.
(Another way to fix this would be to restore the 755 permissions on `clang-tidy-cache.py` (not the usual practice for source files in a Python package). Or `clang-tidy` could call the pip-installed `clang-tidy-cache` script (but that would require installing on `PATH`).)
=> Fix the 'clang-tidy' wrapper script

src/ctcache/clang_tidy_cache.py
After thinking about the tool a bit, I concluded that the Clang-Tidy configuration also needs to be included in the hash. The (not so much documented) option `--directories_with_clang_tidy=...` could help there. However, I think that's not as handy as I want it to be. I think this has to be done by default. Furthermore, this flag could include configuration files which are even not of relevance for the processed file. 
Therefore, I was hunting a more generic solution. My proposal here uses the Clang-Tidy tool itself. I'm asking it to dump the configuration for the file to be processed. In this way I don't have to scan for `.clang-tidy` files, but let Clang-Tidy handle that. This would even work if the user uses Clang-Tidy command line option `--config-file`. 
Of course, the drawback of …
=> Always include the Clang-Tidy config in the hash

src/ctcache/clang_tidy_cache.py
Fix the usage of `==` instead of `is`, `is` is more correct and Pythonic, and more consistent with the project as it is used in the other file for comparison against [None](https://github.com/matus-chochlik/ctcache/blob/0c0de7d63eff775d9bbcf10f69cab5d9e2c43f4c/src/ctcache/clang_tidy_cache_server.py#L386).
remove duplicate import for the `sys` module.
=> Replace == with is; remove duplicate import

README.md, src/ctcache/clang_tidy_cache.py
Implements the feature described in https://github.com/matus-chochlik/ctcache/issues/66.
With this change, and the opt-in flag of `CTCACHE_KEEP_COMMENTS`, I was able to tweak `// NOLINT` suppressions and trigger cache invalidation. The only drawback is the much bigger input to the hash function (in our case I saw up to 33% increase in the input with comments retained). Ideally, we'd be able to strip any comments that don't contain `.*NOLINT.*` but that'd require another pass over pre-processor output with matching comment lexing logic which could be bug-ridden.
=> Add support to retain comments in hash input.

README.md, src/ctcache/clang_tidy_cache.py
Fixes #75 
This adds timeouts to redis remote backend
I used the same [defaults timeouts as ccache](https://ccache.dev/manual/4.10.2.html#_redis_storage_backend)
Perhaps we could have a slightly longer connect timeout default.
=> Add redis socket timeouts

README.md, src/ctcache/clang_tidy_cache.py
This adds two options which are potentially useful for a redis cache deployment.
* specify redis db other than 0
* set a TTL on cache entries, also refreshed on reads
=> Additional redis settings

src/ctcache/clang_tidy_cache.py
Runtime Error:
Loading compile command DB failed: NameError("name 'JSONDecodeError' is not defined")
=> fix 'JSONDecodeError' is not defined.

README.md, src/ctcache/clang_tidy_cache.py
This adds `CTCACHE_LOG_LEVEL` to allow setting it to a different level than `WARNING` (the default) to enable more verbose logging.
I've also added a couple of debug traces that we find useful.
To give you some context, we want to debug for which files `clang-tidy-cache` is reusing the cache and for which ones it's not. Since CMake doesn't provide a way to (as far as I know) to get the output of the clang-tidy call, I ended up creating yet another wrapper for `clang-tidy-cache` that appends to a temp file the output after setting `CTCACHE_LOG_LEVEL=debug`: https://github.com/ClickHouse/ClickHouse/pull/83153
=> Add CTCACHE_LOG_LEVEL to allow more verbose logging

README.md, src/ctcache/clang_tidy_cache.py, src/ctcache/clang_tidy_cache_server.py
This PR adds a simply authentication mechanism for writes.
This allows you to have a public server for reads to speed up developer builds (for example) and do writes on CI where secrets are available.
New environment variable for client: `CTCACHE_AUTH_KEY`, this will be passed as `key` query parameter when making `PUT` requests (i.e. when cache is updated).
`purge_cache` should be called as`DELETE` HTTP method when the auth key is set, in the future it should probably be made DELETE-only, but I kept it for backward compatibility
The auth key can be set up for the server with the `--auth-key-writes` parameter. Allowing for potentially also adding an auth key for reads.
=> add simple authentication mechanism for writes
